const path = require("path");

module.exports = {
    entry: "./src/index.tsx",
    module: {
        rules: [
            // css-modules config
            {
                test: /\.css$/,
                use: [
                    "style-loader",
                    {
                        loader: "@teamsupercell/typings-for-css-modules-loader", options: {
                            banner: '// autogenerated by typings-for-css-modules-loader',
                            formatter: 'prettier',
                        }
                    },
                    {
                        loader: "css-loader",
                        options: { modules: true }
                    }
                ]
            },
            // All files with a '.ts' or '.tsx' extension will be handled by 'ts-loader'.
            { test: /\.tsx?$/, exclude: /node_modules/, loader: "ts-loader" },
            // All output '.js' files will have any sourcemaps re-processed by 'source-map-loader'.
            { test: /\.js$/, loader: "source-map-loader" },
        ]
    },
    resolve: { extensions: ["*", ".ts", ".tsx", ".js", ".jsx"] },
    devtool: "inline-source-map",
    output: {
        // path: path.resolve(__dirname, "public/"),
        // Path found on webpack's example docs
        path: path.resolve(__dirname, 'dist/assets'),
        filename: "bundle.js"
    },
};
